### ISSUE TITLE
Garbage Collector in java

### ISSUE THREAD

**Issue by Alleny244** [TesseractCoding/NeoAlgo#2426]
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)
Yes
## Motivation

(Please outline the motivation for the proposal.)
 Java program to demonstrate the use of garbage collector.
## Pitch

(Please explain why this feature should be implemented and how it would be used.)
This is a important concept in dynamic memory allocation in java Being a part of the GSSOC'21, I would like to implement this in java .Please do assign this to me

**Comment by HarshCasper** [comment]
We don't need to have language-specific implementations around here.
