### ISSUE TITLE
I want to add a algorithm in C++ to add the number stored in two linked lists in the others section of the repo 

### ISSUE THREAD

**Issue by pranjwalsingh236** [TesseractCoding/NeoAlgo#2897]
## 🚀 Feature

You are given two non-empty linked lists representing two non-negative integers. The digits are stored in reverse order, and each of their nodes contains a single digit. Add the two numbers and return the sum as a linked list.
You may assume the two numbers do not contain any leading zero, except the number 0 itself.
Question Link: https://leetcode.com/problems/add-two-numbers/

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES!!

## Motivation

I love to solve new and interesting questions, while I was solving this problem I learnt many new things related to linked lists and pointers and felt that this problem is very good and interesting for problem-solving enthusiasts.

## Pitch

As we all Know linked lists is one of the most famous topics in programming world and a very important DSA  concept. While solving a linked list problem one should understand the importance of the pointers and using them to solve the problem. I hope this problem helps many to understand the correct way of defining the pointers and linked lists. I would like to contribute my approach to this problem using the traversing the elements of linked lists in c++.
Hey, @bhav09 please look into this issue and please assign this to me under GSSOC2021.
Thank you.

**Comment by ankitaggarwal23** [comment]
@pranjwalsingh236 Hi, I assigned you. Happy Coding!😊

**Comment by bhav09** [comment]
Thanks, @ankitaggarwal23 :)
